version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  pre_build:
    commands:
      - echo Initializing environment
      - export CODEARTIFACT_AUTH_TOKEN=`aws codeartifact get-authorization-token --domain devops --domain-owner 123456789012 --region us-east-2 --query authorizationToken --output text`
      - export CODEARTIFACT_MAVEN_REPO_URL=`aws codeartifact get-repository-endpoint --domain devops --domain-owner 123456789012 --repository webapp-cicd --format maven --region us-east-2 --query repositoryEndpoint --output text`
      - mkdir -p ~/.m2
      - |
        cat > settings.xml <<EOF
        <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
                  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                  xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 https://maven.apache.org/xsd/settings-1.0.0.xsd">
          <servers>
            <server>
              <id>codeartifact</id>
              <username>aws</username>
              <password>${CODEARTIFACT_AUTH_TOKEN}</password>
            </server>
          </servers>
          <mirrors>
            <mirror>
              <id>codeartifact</id>
              <mirrorOf>*</mirrorOf>
              <url>${CODEARTIFACT_MAVEN_REPO_URL}</url>
            </mirror>
          </mirrors>
        </settings>
        EOF

  build:
    commands:
      - echo Build started on `date`
      - mvn -s settings.xml compile
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn -s settings.xml package
artifacts:
  files:
    - target/devops-web-project.war
  discard-paths: no
